### ISSUE TITLE
User: See events, register for events, see registered events, unregister from events.

### ISSUE THREAD

**Issue by WSMorrison** [WSMorrison/Hard_Parkers#41]
As the **basic user**, I will be able to **interact with the site and the site will interact back**.

Acceptance
- Users will be able to see a list of all upcoming events.
- Users will be able to see a list of all upcoming events they are registered for.
- Users will be able to register for an event.
- Users will be able to unregister for an event.
- Users will not be able to sign up for events after the registration closed date.
- Users will no longer see past events on either list.

Tasks:
- [ ] Create an index page with a list of upcoming events.
  - [ ] View
  - [ ] URL
- [ ] Create an events page with a list of the events the user is signed up for.
  - [ ] View
  - [ ] URL
- [ ] Create a registration button, and confirmation page.
  - [ ] View
  - [ ] URL
  - [ ] Confirmation page pass back to **list of events registered for**
    - [ ] View
    - [ ] URL 
- [ ] Create an unregistration button, and confirmation page.
  - [ ] View
  - [ ] URL
  - [ ] Confirmation page should pass back to **list of all events.**
 
#1, #2, #3, #4, #13, #34
