### ISSUE TITLE
Organizer: Create, edit, delete events.

### ISSUE THREAD

**Issue by WSMorrison** [WSMorrison/Hard_Parkers#42]
As the **organizer**, I will be able to **create, edit, and delete events**, as well as **see a list of events they organized.**

Acceptance
- The organizer will be able to access a form to create an event.
- The organizer can access an edit for that will prepopulate with the existing event details.
- The organizer can delete an event.
- The organizer can view a list of their events, with access to edit, delete the events.
- The organizer will also be able to see a printable list of the attendees for their event.

Tasks:
- [ ] Create an organizer page that will show a list of their events plus a create event button.
  - [ ] View
  - [ ] URL
- [ ] Create a blank event form
  - [ ] View
  - [ ] URL
  - [ ] Crispy form   
- [ ] Create an event edit form, prepopulated with event details.
  - [ ] View - prepopulate code lives here.
  - [ ] URL 
- [ ] Create a delete confirmation page.
  - [ ] View
  - [ ] URL 
- [ ] Create an attendee list page.
  - [ ] View
  - [ ] URL 
  
#5, #6, #7, #8, #14, #26
